=== cmur2/ssim-ed/assets/input/sed-mapping-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://mycrobase.de/sed-mapping-1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://mycrobase.de/sed-mapping-1.0">

    <xs:element name="mappings" type="mappingsType"></xs:element>

    <xs:complexType name="mappingsType">
    	<xs:sequence>
    		<xs:element name="map" type="mapType" maxOccurs="unbounded"
    			minOccurs="0">
    		</xs:element>
    	</xs:sequence>
    	<xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="mapType">
    	<xs:attribute name="key" type="xs:string" use="optional">
    		<xs:annotation>
    			<xs:documentation>Key constant (suffix after KEY_) from com.jme3.input.KeyInput - don't use at the same time with button or axis!</xs:documentation>
    		</xs:annotation>
    	</xs:attribute>
    	<xs:attribute name="button" type="xs:string" use="optional">
    		<xs:annotation>
    			<xs:documentation>Mouse button constant (suffix after BUTTON_) from com.jme3.input.MouseInput - don't use at the same time with key or axis!</xs:documentation>
    		</xs:annotation>
    	</xs:attribute>
    	<xs:attribute name="axis" type="xs:string" use="optional">
    		<xs:annotation>
    			<xs:documentation>Mouse axis constant (suffix after AXIS_) from com.jme3.input.MouseInput - don't use at the same time with key or button!</xs:documentation>
    		</xs:annotation>
    	</xs:attribute>
    	<xs:attribute name="negative" type="xs:boolean" use="optional">
            <xs:annotation>
                <xs:documentation>Only useful in junction with axis attribute.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    	<xs:attribute name="action" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== cmur2/ssim-ed/assets/input/keys_de.xml
<?xml version="1.0" encoding="UTF-8"?>
<sed:mappings id="de" xmlns:sed="http://mycrobase.de/sed-mapping-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mycrobase.de/sed-mapping-1.0 sed-mapping-1.0.xsd">
    
    <!--
    <map key="C" action="SIMPLEAPP_CameraPos" />
    <map key="M" action="SIMPLEAPP_Memory" />
    <map key="F5" action="SIMPLEAPP_HideStats" />
    -->
    
    <map key="LEFT" action="FLYCAM_Left" />
    <map axis="X" negative="true" action="FLYCAM_Left" />
    <map key="RIGHT" action="FLYCAM_Right" />
    <map axis="X" negative="false" action="FLYCAM_Right" />
    <map key="UP" action="FLYCAM_Up" />
    <map axis="Y" negative="false" action="FLYCAM_Up" />
    <map key="DOWN" action="FLYCAM_Down" />
    <map axis="Y" negative="true" action="FLYCAM_Down" />
    <map key="A" action="FLYCAM_StrafeLeft" />
    <map key="D" action="FLYCAM_StrafeRight" />
    <map key="W" action="FLYCAM_Forward" />
    <map key="S" action="FLYCAM_Backward" />
    <map key="Q" action="FLYCAM_Rise" />
    <map key="Y" action="FLYCAM_Lower" />
    <map axis="WHEEL" negative="false" action="FLYCAM_ZoomIn" />
    <map axis="WHEEL" negative="true" action="FLYCAM_ZoomOut" />
    
    <map key="ESCAPE" action="SED_Pause" />
    
    <map key="F6" action="SED_ShowGrid" />
    <map key="F9" action="SED_SpeedDown" />
    <map key="F10" action="SED_SpeedUp" />
    
</sed:mappings>

=== cmur2/ssim-ed/assets/input/keys_default.xml
<?xml version="1.0" encoding="UTF-8"?>
<sed:mappings id="default" xmlns:sed="http://mycrobase.de/sed-mapping-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mycrobase.de/sed-mapping-1.0 sed-mapping-1.0.xsd">
    
    <!--
        This mapping set serves only one need: to disable all mappings
        hard-coded into jME to avoid double mappings and to restore them
        on interest. Therefore this mapping set should cover all mappings
        found in jME classes and only them. Other mapping sets may (and should)
        go beyond this limit but not this one!
    -->
    
    <map key="ESCAPE" action="SIMPLEAPP_Exit" />
    <map key="C" action="SIMPLEAPP_CameraPos" />
    <map key="M" action="SIMPLEAPP_Memory" />
    <map key="F5" action="SIMPLEAPP_HideStats" />
    
    <map key="LEFT" action="FLYCAM_Left" />
    <map key="RIGHT" action="FLYCAM_Right" />
    <map key="UP" action="FLYCAM_Up" />
    <map key="DOWN" action="FLYCAM_Down" />
    
    <map key="A" action="FLYCAM_StrafeLeft" />
    <map key="D" action="FLYCAM_StrafeRight" />
    <map key="W" action="FLYCAM_Forward" />
    <map key="S" action="FLYCAM_Backward" />
    
    <map key="Q" action="FLYCAM_Rise" />
    <map key="Z" action="FLYCAM_Lower" />
    
    <map button="LEFT" action="FLYCAM_RotateDrag" />
    
</sed:mappings>
