=== cmur2/ssim-ed/assets/weather/sed-weather-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://mycrobase.de/sed-weather-1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://mycrobase.de/sed-weather-1.0">
    <xs:element name="weather" type="weatherType" />
    
    <xs:complexType name="weatherType">
    	<xs:sequence>
    		<xs:element name="sky" type="skyType"></xs:element>
    		<xs:element name="sun" type="sunType"></xs:element>
    		<xs:element name="ocean" type="oceanType"></xs:element>
    		<xs:element name="cloud" type="cloudType"></xs:element>
    		<xs:element name="precipitation" type="precipitationType"></xs:element>
    		<xs:element name="wind" type="windType"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="skyType">
    	<xs:sequence>
    		<xs:element name="turbidity">
    			<xs:simpleType>
    				<xs:restriction base="xs:float">
    					<xs:minInclusive value="2"></xs:minInclusive>
    					<xs:maxInclusive value="30"></xs:maxInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="light" type="Vector3f">
    		</xs:element>
    		
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="sunType">
    	<xs:sequence>
    		<xs:element name="lensflare" type="sunLensflareType"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="cloudType">
    	<xs:sequence>
    		<xs:element name="cover">
    			<xs:simpleType>
    				<xs:restriction base="xs:int">
    					<xs:minInclusive value="0"></xs:minInclusive>
    					<xs:maxInclusive value="255"></xs:maxInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="sharpness">
    			<xs:simpleType>
    				<xs:restriction base="xs:float">
    					<xs:minInclusive value="0"></xs:minInclusive>
    					<xs:maxInclusive value="1"></xs:maxInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="way-factor">
    			<xs:simpleType>
    				<xs:restriction base="xs:float">
    					<xs:minInclusive value="0"></xs:minInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="zoom" type="xs:int"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="oceanType"></xs:complexType>

    <xs:complexType name="windType">
    	<xs:sequence>
    		<xs:element name="direction">
                <xs:annotation>
                	<xs:documentation>Specifies the direction from which the wind is coming i.e. source direction in degrees.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
    				<xs:restriction base="xs:float">
    					<xs:minInclusive value="0"></xs:minInclusive>
    					<xs:maxInclusive value="359"></xs:maxInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="strength">
                <xs:annotation>
                	<xs:documentation>Specifies the strength of the wind in kn (knots).</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
    				<xs:restriction base="xs:float">
    					<xs:minInclusive value="0"></xs:minInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="sunLensflareType">
    	<xs:sequence>
    		<xs:element name="enabled" type="xs:boolean"></xs:element>
    		<xs:element name="shininess">
    			<xs:simpleType>
    				<xs:restriction base="xs:float">
    					<xs:minInclusive value="0"></xs:minInclusive>
    					<xs:maxInclusive value="1"></xs:maxInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="precipitationType">
        <xs:sequence>
            <xs:element name="form">
                <xs:annotation>
                    <xs:documentation>Specifies the type of precipitation, valid values from this enumeration: 0 - none, 1 - rain (RA), 2 - ice pellets (PL), 3 - snow (SN)</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:enumeration value="0"></xs:enumeration>
                        <xs:enumeration value="1"></xs:enumeration>
                        <xs:enumeration value="2"></xs:enumeration>
                        <xs:enumeration value="3"></xs:enumeration>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="intensity">
                <xs:simpleType>
                    <xs:restriction base="xs:float">
                        <xs:minInclusive value="0"></xs:minInclusive>
                        <xs:maxInclusive value="1"></xs:maxInclusive>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="Vector3f">
        <xs:annotation>
        	<xs:documentation>A Vector is a tuple made out of three float components.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
    		<xs:pattern value="\(.+,.+,.+\)"></xs:pattern>
    	</xs:restriction>
    </xs:simpleType>
</xs:schema>

=== cmur2/ssim-ed/assets/weather/heavy_rain.xml
<?xml version="1.0" encoding="UTF-8"?>
<sed:weather id="heavy_rain" xmlns:sed="http://mycrobase.de/sed-weather-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mycrobase.de/sed-weather-1.0 sed-weather-1.0.xsd">
    <air>
        <turbidity>4.0</turbidity>
    </air>
    <sky>
        <light>(0.18, 0.18, 0.18)</light>
    </sky>
    <sun>
        <lensflare>
            <enabled>false</enabled>
            <shininess>0.95</shininess>
        </lensflare>
    </sun>
    <ocean>
        <a-factor>0.001</a-factor>
        <wave-cutoff>1.0</wave-cutoff>
        <height-scale>0.1</height-scale>
        <choppiness>0.05</choppiness>
    </ocean>
    <cloud>
        <cover>50</cover>
        <sharpness>0.96</sharpness>
        <way-factor>0.005</way-factor>
        <zoom>40</zoom> <!-- static value -->
    </cloud>
    <precipitation>
        <form>1</form>
        <intensity>1.0</intensity>
    </precipitation>
    <wind>
        <!-- from south -->
        <direction>90</direction>
        <strength>15</strength>
    </wind>
</sed:weather>

=== cmur2/ssim-ed/assets/weather/clear.xml
<?xml version="1.0" encoding="UTF-8"?>
<sed:weather id="clear" xmlns:sed="http://mycrobase.de/sed-weather-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mycrobase.de/sed-weather-1.0 sed-weather-1.0.xsd">
    <air>
        <turbidity>2.0</turbidity>
    </air>
    <sky>
        <light>(0.2, 0.2, 0.2)</light>
    </sky>
    <sun>
        <lensflare>
            <enabled>true</enabled>
            <shininess>0.95</shininess>
        </lensflare>
    </sun>
    <ocean />
    <cloud>
        <cover>100</cover>
        <sharpness>0.96</sharpness>
        <way-factor>0.005</way-factor>
        <zoom>40</zoom> <!-- static value -->
    </cloud>
    <precipitation>
        <form>0</form>
        <intensity>0.0</intensity>
    </precipitation>
    <wind>
        <!-- from north west -->
        <direction>315</direction>
        <strength>0</strength>
    </wind>
</sed:weather>
